version: "3.9"
services:
  fossbilling:
    image: evrifaessa/fossbilling
    restart: always
    ports:
      - 8080:80
    volumes:
      - fossbilling:/var/www/html
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - 3036:3036
      - 30360:30360         
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - mysql:/var/lib/mysql

volumes:
  fossbilling:
  mysql: